-- Before
try
  -- Inside
  -- ${(() => { throw new Error("ERROR!") })()}
  @catch|err|
    -- ${err.message}

-- After
